INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (13, 68, 3, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (17, 68, 3, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (13, 69, 4, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (14, 70, 5, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (10, 70, 4, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (17, 65, 1, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (17, 69, 5, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (19, 73, 4, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (13, 73, 4, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (13, 65, 5, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (14, 71, 4, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (14, 68, 5, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (15, 73, 3, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (18, 72, 5, INSERT INTO public.detail_rent (rent_id, item_id, qty,) 
VALUES (16, 67, 1, INSERT INTO public.detail_rent (rent_id, item_id, qty,)